/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { OgamaToken } from './OgamaToken.js';
export * as factories from './factories/index.js';
export { OgamaToken__factory } from './factories/OgamaToken__factory.js';